doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        'TomaszBartusiakRekrutacjaSmartiveapp\Module\Thumbnail\Infrastructure\Persistence\Migrations': '%kernel.project_dir%/src/Module/Thumbnail/Infrastructure/Persistence/Migrations'
    enable_profiler: false
